### ISSUE TITLE
Support for older python versions

### ISSUE THREAD

**Issue by nassersaazi** [rajtilakjee/langchain-cli#2]
I am getting this error when trying to install `langchain-cli` with pip

`
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.11,<4.0
ERROR: Could not find a version that satisfies the requirement langchain-cli (from versions: none)
ERROR: No matching distribution found for langchain-cli`

I am running version `3.10.6`. I know a solution would be to upgrade, but wouldn't it be a plus if the project supported versions of python 3 earlier that 3.11?

**Comment by rajtilakjee** [comment]
@nassersaazi definitely it would be helpful. Will accomodate version >= 3.8.1 for Python.

**Comment by rajtilakjee** [comment]
@nassersaazi Added support for Python versions 3.8.1 and above.
